services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "${DEV_PORT}:${DEV_PORT}"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - DEV_PORT=${DEV_PORT}
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}